services:
  # SERVICE UNIQUE DOCKER : Le Moteur de détection (SOC / IPS)
  soc-moteur:
    build: .
    container_name: soc-moteur-container
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./network_traffic.log:/app/network_traffic.log
    restart: always
